---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```



```{r message = FALSE, echo = FALSE}
set.seed(12345) #set fixed random samples

noaa_dfc = 
  ny_noaa %>%
  sample_n(10000) %>%
  separate(col = date, into = c("year","month", "day")) %>%
  mutate(across(.cols
                = c(year, month, day), as.integer)) %>%
  mutate(month = month.name[month]) %>%
  mutate(prcp = prcp/10, 
         tmax = as.numeric(tmax)/10,
         tmin = as.numeric(tmin)/10) 
```



Column {data-width=500}
-----------------------------------------------------------------------

### Chart A

```{r}
noaa_dfc %>%
  drop_na(tmin, tmax) %>%
  filter(year == 1997) %>%
  mutate(text_label = str_c("Max Temperature: ", tmax, 
                            "\nMin Temperature: ", tmin, 
                            "\nDate: ", month,"-",day,"-",year)) %>%
  plot_ly(x = ~ tmin, 
          y = ~ tmax,
          type = "scatter",
          mode = "markers",
          alpha = 0.5,
          color = ~ month,
          colors = "viridis", 
          text = ~ text_label) %>%
  layout(title = 
           "Minimum Temperature vs. Maximum Temperature in 1997",
         xaxis = 
           list(title = 
                  "Minimum temperature (ºC) in 1997"),
         yaxis = 
           list(title = 
                  "Maximum temperature (ºC) in 1997"))
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart B

```{r}
noaa_dfc %>%
  drop_na(tmin, tmax) %>%
  mutate(month = 
           fct_reorder(month, tmax)) %>%
  group_by(year, month, id) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  plot_ly(x = ~ month, 
          y = ~ factor(mean_tmax), 
          color = ~ month, 
          colors = "viridis", 
          type = "box") %>%
  layout(
    title = 
      "Max Temperature (Average) Pattern for Each Month (1981-2010)", 
    xaxis = 
      list(title = 
             "Month"),
    yaxis = 
      list(title = 
             "(Mean) Max Temperature (ºC)")) 
```

### Chart C

```{r}
noaa_dfc %>%
  filter(snow > 0 & snow < 200,
         year > 1996 & year <= 2010) %>% 
  plot_ly(x = ~ year, 
          y = ~ snow, 
          split = ~ year, 
          type = "violin",
          box = list(visible = T, 
          meanline = list(visible = T))) %>%
  layout(title = 
           "Snowfall Distribution (1997-2010)",
         xaxis = 
           list(title = 
                  "Year (1997-2010)"),
         yaxis = 
           list(title = 
                  "Snowfall (mm)"))
```


### Chart D
```{r}
noaa_dfc %>%
  filter(snow > 0,
         year == 1997) %>%
  mutate(month = 
           fct_reorder(month, snow)) %>%
  group_by(month) %>%
  summarize(mean_snow 
            = mean(snow))  %>%
  plot_ly(x = ~ month, 
          y = ~ mean_snow, 
          color = ~ month, 
          colors = "viridis", 
          type = "bar") %>%
   layout(title = 
           "Average Snowfall for Months in 1997",
         xaxis = 
           list(title = 
                  "Month"),
         yaxis = 
           list(title = 
                  "Mean Snowfall (mm)"))
```


