---
title: "Resume"
output: 
  html_document:
    toc: True
    toc_float: True
---

### Education

**Columbia University** <div style="text-align: right"> *New York, NY* </div>

Master of Science (M.S.) Biostatistics

- Theory and Methods Track
- Expected Graduation: Spring 2023 (May)

**UC Irvine** <div style="text-align: right"> *Irvine, CA* </div>

Bachelor of Science (B.S.) Computer Science and Engineering  

- Graduated: Spring 2020




### Research

**Computational Biology/Neuroscience Research Intern**
UC Irvine Neuroscience <div style="text-align: right"> *Jun 2018 - Jun 2021* </div>

- Projects examine episodic and working memory roles in decisions for reward, perceptual inference, drug choice and addiction, and inter temporal choice, using computational model-driven analysis of behavior and brain activity (via fMRI, but with plans for EEG and other modalities)
- Programming: MATLAB, R, Python


**Physics Research Intern – Magnetic Linear Accelerator**
Keck Medicine of USC <div style="text-align: right"> *April 2014 - August 2016* </div>

- Created magnetic linear accelerator, Gauss Rifle to study kinetic energy, momentum, velocity, compare to real gun
- Awarded Second Place at the USC Keck Science and engineering fair in the field of Physics


### Work

**UCI Math CEO Mentor**
UC Irvine Math <div style="text-align: right"> *Jun 2018 - March 2020* </div>

- Every week, middle-school students come to UCI to partake in mathematical workshops (I teach them learn new mathematical topics, help them understand mathematical concepts/games and puzzles).



<br>
<center>

Tanvir.K Resume [Resume](TKResume.pdf). 


Click here to return to the [Home](index.html) page.
