---
title: "Plots"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: true
---



```{r message = FALSE, echo = FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```



```{r message = FALSE, echo = FALSE}
data("ny_noaa") 
```

### Loading Data "ny_noaa"
#### Data were accessed from the NOAA National Climatic Data Center
```{r message = FALSE}
set.seed(12345) 

noaa_dfc = 
  ny_noaa %>%
  sample_n(10000) %>%
  separate(col = date, 
           into = c("year","month", "day")) %>%
  mutate(across(.cols
                = c(year, month, day), as.integer)) %>%
  mutate(month = month.name[month]) %>%
  mutate(prcp = prcp/10, 
         tmax = as.numeric(tmax)/10,
         tmin = as.numeric(tmin)/10) 
```





### Plotly scatterplot
#### Maximum Temperature vs. Minimum Temperature in 1997
```{r message = FALSE}
noaa_dfc %>%
  drop_na(tmin, tmax) %>%
  filter(year == 1997) %>%
  mutate(text_label = 
           str_c("Max Temperature: ", tmax, 
                            "\nMin Temperature: ", tmin, 
                            "\nDate: ", month,"-",day,"-",year)) %>%
  plot_ly(x = ~ tmin, 
          y = ~ tmax,
          type = "scatter",
          mode = "markers",
          alpha = 0.5,
          color = ~ month,
          colors = "viridis", 
          text = ~ text_label) %>%
  layout(xaxis = list(title = 
                        "Minimum temperature (ºC) in 1997"),
         yaxis = list(title = 
                        "Maximum temperature (ºC) in 1997"))
```


### Plotly Boxplot
#### Max Temperature (Average) in Each Station (1981 to 2010)
```{r message = FALSE}
noaa_dfc %>%
  drop_na(tmin, tmax) %>%
  mutate(month = 
           fct_reorder(month, tmax)) %>%
  group_by(year, month, id) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  plot_ly(x = ~ month, 
          y = ~ factor(mean_tmax), 
          color = ~ month, 
          colors = "viridis", 
          type = "box") %>%
  layout(
    title = 
      "Max Temperature (Average) in Each Station (1981 to 2010)",
    xaxis = list(title = 
                   "Month"),
    yaxis = list(title = 
                   "(Mean) Max Temperature (ºC)")) 
```


### Plotly Violinplot 
#### 
```{r message = FALSE}
noaa_dfc %>%
  filter(snow > 0 & snow < 200) %>% 
  plot_ly(x = ~ year, 
          y = ~ snow, 
          split = ~ year, 
          type = "violin",
          box = list(visible = T, 
          meanline = list(visible = T))) %>%
  layout(xaxis = list(title = "Year (1981-2010)"),
         yaxis = list(title = "Snowfall (mm)"))
```




Click here to return to the [Home](index.html) page.